[metadata]
name    = "storm"
author  = "ave"

[global]
plan    = "storm"
case    = "storm"
builder = "docker:go"
runner  = "cluster:k8s"
total_instances = 10

[global.build_config]
push_registry=true
registry_type="aws"

[global.run_config]


[[groups]]
id = "first"
instances = { count = 10 }

  [groups.run.test_params]
  conn_count = '1'
  conn_outgoing = '5'
  conn_delay_ms = '3000'
  concurrent_dials = '1'
  data_size_kb     = '20'
